Argus/Models/Login.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Argus.Models
{
    public class Login
    {
        public string Password { get; set; }
    }
}

Argus/Controllers/ArgusController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Argus.Models;

namespace Argus.Controllers
{
    public class ArgusController : Controller
    {
        // GET: Argus
        [HttpGet]
        public ActionResult Index()
        {
            ViewBag.ErrorLabel = "";
            return View();
        }

        [HttpPost]
        public ActionResult Index(Login lng)
        {
            if (lng.Password == null)
            {
                ViewBag.ErrorLabel = "Please Enter Administrator Password";
                return View();
            }
            if (lng.Password.Trim() != "1234")
            {
                ViewBag.ErrorLabel = "Administrator Password is incorrect";
                return View();
            }
            return RedirectToAction("Home");
        }

        public ActionResult Home()
        {
            return View();
        }
        public ActionResult About()
        {
            return View();
        }

        public ActionResult Calculator()
        {
            return View();
        }

        public ActionResult Graph_StudentsbyMajor()
        {
            return View();
        }

        public ActionResult Graph_StudentsbyStates()
        {
            return View();
        }

        public ActionResult Graph_StudentsFieldDistribution()
        {
            return View();
        }

        public ActionResult Graph_StudentsbyResidencyType()
        {
            return View();
        }

        public ActionResult Graph_EmploymentProjection()
        {
            return View();
        }

        public ActionResult Graph_EmploymentAccordingtoIndustry()
        {
            return View();
        }
    }
}

Argus/Views/Argus/About.cshtml
@{
    ViewBag.Title = ViewBag.P_SiteName;
    ViewBag.Description = ViewBag.P_Description;
    ViewBag.Keywords = ViewBag.P_KeyWord;
    Layout = "~/Views/Shared/_LayoutMain.cshtml";
}

Argus/Views/Argus/Graph_EmploymentAccordingtoIndustry.cshtml
@{
    ViewBag.Title = ViewBag.P_SiteName;
    ViewBag.Description = ViewBag.P_Description;
    ViewBag.Keywords = ViewBag.P_KeyWord;
    Layout = "~/Views/Shared/_LayoutGraph.cshtml";
}

<iframe id="main" style="width:100%;height:700px;padding:10px" src="https://app.powerbi.com/view?r=eyJrIjoiYzE0NjlkYTgtMGE2MS00OWU0LWFhMzAtYmI1MWRiZTg1NmMzIiwidCI6IjRkZTQ0ZDVhLTBjMzQtNDE5Zi05YTc0LWNlMWRjZDRjZWY5OSJ9" frameborder="0" allowFullScreen="true"></iframe>

Argus/Views/Argus/Graph_EmploymentProjection.cshtml
@{
    ViewBag.Title = ViewBag.P_SiteName;
    ViewBag.Description = ViewBag.P_Description;
    ViewBag.Keywords = ViewBag.P_KeyWord;
    Layout = "~/Views/Shared/_LayoutGraph.cshtml";
}

<iframe id="main" style="width:100%;height:700px;padding:10px" src="https://app.powerbi.com/view?r=eyJrIjoiMjU2OWQzYzAtZTMzMS00YzZkLTkxYjEtMWJhODAxOWQwZjhlIiwidCI6IjRkZTQ0ZDVhLTBjMzQtNDE5Zi05YTc0LWNlMWRjZDRjZWY5OSJ9" frameborder="0" allowFullScreen="true"></iframe>

Argus/Views/Argus/Graph_StudentsFieldDistribution.cshtml
@{
    ViewBag.Title = ViewBag.P_SiteName;
    ViewBag.Description = ViewBag.P_Description;
    ViewBag.Keywords = ViewBag.P_KeyWord;
    Layout = "~/Views/Shared/_LayoutGraph.cshtml";
}

<iframe id="main" style="width:100%;height:700px;padding:10px" src="https://app.powerbi.com/view?r=eyJrIjoiYTg0NjgzMTYtNTFmOC00ZDA4LWExYzgtMjI3Mzg3ZDdlZGYyIiwidCI6IjRkZTQ0ZDVhLTBjMzQtNDE5Zi05YTc0LWNlMWRjZDRjZWY5OSJ9" frameborder="0" allowFullScreen="true"></iframe>

Argus/Views/Argus/Graph_StudentsbyMajor.cshtml
@{
    ViewBag.Title = ViewBag.P_SiteName;
    ViewBag.Description = ViewBag.P_Description;
    ViewBag.Keywords = ViewBag.P_KeyWord;
    Layout = "~/Views/Shared/_LayoutGraph.cshtml";
}

<iframe id="main" style="width:100%;height:700px;padding:10px" src="https://app.powerbi.com/view?r=eyJrIjoiZjA5YzEwM2QtNjU3Mi00NTZkLTljYmMtNjExZWQxN2U0MjkxIiwidCI6IjRkZTQ0ZDVhLTBjMzQtNDE5Zi05YTc0LWNlMWRjZDRjZWY5OSJ9" frameborder="0" allowFullScreen="true"></iframe>

Argus/Views/Argus/Graph_StudentsbyResidencyType.cshtml
@{
    ViewBag.Title = ViewBag.P_SiteName;
    ViewBag.Description = ViewBag.P_Description;
    ViewBag.Keywords = ViewBag.P_KeyWord;
    Layout = "~/Views/Shared/_LayoutGraph.cshtml";
}

<iframe id="main" style="width:100%;height:700px;padding:10px" src="https://app.powerbi.com/view?r=eyJrIjoiNTZhYTQ5MGItZDg2Mi00ODg0LWJhMzctYzE4MDUzNGYzMGVlIiwidCI6IjRkZTQ0ZDVhLTBjMzQtNDE5Zi05YTc0LWNlMWRjZDRjZWY5OSJ9" frameborder="0" allowFullScreen="true"></iframe>

Argus/Views/Argus/Graph_StudentsbyStates.cshtml
@{
    ViewBag.Title = ViewBag.P_SiteName;
    ViewBag.Description = ViewBag.P_Description;
    ViewBag.Keywords = ViewBag.P_KeyWord;
    Layout = "~/Views/Shared/_LayoutGraph.cshtml";
}

<iframe id="main" style="width:100%;height:700px;padding:10px" src="https://app.powerbi.com/view?r=eyJrIjoiYTA1ZGU2YTAtMDdjNS00N2QxLTg1NDMtNDFjMjg2ZmU3YWJiIiwidCI6IjRkZTQ0ZDVhLTBjMzQtNDE5Zi05YTc0LWNlMWRjZDRjZWY5OSJ9" frameborder="0" allowFullScreen="true"></iframe>

Argus/Views/Argus/Home.cshtml
@{
    ViewBag.Title = ViewBag.P_SiteName;
    ViewBag.Description = ViewBag.P_Description;
    ViewBag.Keywords = ViewBag.P_KeyWord;
    Layout = "~/Views/Shared/_LayoutMain.cshtml";
}

<!-- Modal -->
<div id="myModal" class="modal fade" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title" style="color:maroon">WARNING : Disclaimer for Argus</h4>
            </div>
            <div class="modal-body">
                <p style="text-align:justify;text-justify:trim;color:#2e2d2d">
                    We are doing our best to prepare the content of this site. However, for Argus cannot warranty the expressions and suggestions of the contents, as well as its accuracy. In addition, to the extent permitted by the law, for Argus shall not be responsible for any losses and/or damages due to the usage of the information on our website.
                    <br><br>
                    The links contained on our website may lead to external sites, which are provided for convenience only. Any information or statements that appeared in these sites are not sponsored, endorsed, or otherwise approved by for Argus. For these external sites, for Argus cannot be held liable for the availability of, or the content located on or through it. Plus, any losses or damages occurred from using these contents or the internet generally.
                </p>
            </div>
            <div class="modal-footer">
                <div style="width:100%;text-align:left;margin:0px;padding:0px">
                    <div class="checkbox">
                        <label style="color:maroon"><input type="checkbox" id="CBS1">I understand that the information in Argus website may not be accurate</label>
                    </div>
                    <div class="checkbox">
                        <label style="color:maroon"><input type="checkbox" id="CBS2">I acknowledge that before making any decision based on the provided information I have to talk with an expert.</label>
                    </div>
                </div>
                <button type="button" class="btn btn-primary" onclick="cbTest()"><span>Enter To Argus</span></button>
            </div>
        </div>

    </div>
</div>

<button type="button" class="btn btn-primary" id="MCAL" data-toggle="modal" data-target="#myModal" data-backdrop="static" data-keyboard="false" style="visibility:hidden">ModalShow</button>

<div id="main">
    <div class="inner">
        <!-- Boxes -->
        <div class="thumbnails">

            <div class="box">
                <a href="https://youtu.be/s6zR2T9vn2c" class="image fit"><img src="~/Layout/images/1.png" alt="" /></a>
                <div class="inner">
                    <h3 style="font-family:Arial;font-size:16px;font-weight:bold;color:#70c7be">Students by Major</h3>
                    <p style="height:100px;color:#c6c6c6;text-align:justify;text-justify:trim">
                        The graph shows the number of students in each study area by year. A comparison of trends and popularity of each education field can be observed here.
                    </p>
                    <a href="@Url.Action("Graph_StudentsbyMajor","Argus")" class="button fit">Show the Graph</a>
                </div>
            </div>

            <div class="box">
                <a href="https://youtu.be/s6zR2T9vn2c" class="image fit"><img src="~/Layout/images/2.png" alt="" /></a>
                <div class="inner">
                    <h3 style="font-family:Arial;font-size:16px;font-weight:bold;color:#7f92cf">Students by States</h3>
                    <p style="height:100px;color:#c6c6c6;text-align:justify;text-justify:trim">
                        The graph shows the number of students in each state over the period of five years. Also, the map shows the total number of students in each state.
                    </p>
                    <a href="@Url.Action("Graph_StudentsbyStates","Argus")" class="button fit">Show the Graph</a>
                </div>
            </div>

            <div class="box">
                <a href="https://youtu.be/s6zR2T9vn2c" class="image fit"><img src="~/Layout/images/3.png" alt="" /></a>
                <div class="inner">
                    <h3 style="font-family:Arial;font-size:16px;font-weight:bold;color:#9d7ed0">Students Field Distribution</h3>
                    <p style="height:100px;color:#c6c6c6;text-align:justify;text-justify:trim">
                        The charts show a comparison of domestic and international students by their field of education. Furthermore, they illustrate the distribution of education fields in the higher education system in Australia.
                    </p>
                    <a href="@Url.Action("Graph_StudentsFieldDistribution","Argus")" class="button fit">Show the Graph</a>
                </div>
            </div>

            <div class="box">
                <a href="https://youtu.be/s6zR2T9vn2c" class="image fit"><img src="~/Layout/images/4.png" alt="" /></a>
                <div class="inner">
                    <h3 style="font-family:Arial;font-size:16px;font-weight:bold;color:#7f92cf">Students by Residency Type</h3>
                    <p style="height:100px;color:#c6c6c6;text-align:justify;text-justify:trim">
                        The graph shows a comparison of the number of students by year and the year-over-year growth. Also, three years prediction is included in the graph.
                    </p>
                    <a href="@Url.Action("Graph_StudentsbyResidencyType","Argus")" class="button fit">Show the Graph</a>
                </div>
            </div>

            <div class="box">
                <a href="https://youtu.be/s6zR2T9vn2c" class="image fit"><img src="~/Layout/images/5.png" alt="" /></a>
                <div class="inner">
                    <h3 style="font-family:Arial;font-size:16px;font-weight:bold;color:#9d7ed0">Employment Projection</h3>
                    <p style="height:100px;color:#c6c6c6;text-align:justify;text-justify:trim">
                        The graph shows 2023 employment projection across Australia, States, and Cities in different industry.
                    </p>
                    <a href="@Url.Action("Graph_EmploymentProjection","Argus")" class="button fit">Show the Graph</a>
                </div>
            </div>

            <div class="box">
                <a href="https://youtu.be/s6zR2T9vn2c" class="image fit"><img src="~/Layout/images/6.png" alt="" /></a>
                <div class="inner">
                    <h3 style="font-family:Arial;font-size:16px;font-weight:bold;color:#70c7be">Employment According to Industry</h3>
                    <p style="height:100px;color:#c6c6c6;text-align:justify;text-justify:trim">
                        The graph shows the number of each states' employees in each industry. Also, the growth of employment over five years is shown.
                    </p>
                    <a href="@Url.Action("Graph_EmploymentAccordingtoIndustry","Argus")" class="button fit">Show the Graph</a>
                </div>
            </div>

        </div>

    </div>
</div>


<script>
    window.onload = function () {
        var cs = "0";
        cs = sessionStorage.getItem("Argus");
        if (cs != "1") {
            jQuery('#MCAL').click();
        }
       
    };

    function cbTest() {
        var CK1 = document.getElementById("CBS1");
        var CK2 = document.getElementById("CBS2");
        if ((CK1.checked == true) && (CK2.checked == true)) {
            $('#myModal').modal('hide');
            sessionStorage.setItem("Argus", "1");
        }
        else {
            $('#myModal').modal({ backdrop: 'static', keyboard: false })  
        }
    }
</script>

Argus/Views/Argus/Index.cshtml
@model Argus.Models.Login
@{
    ViewBag.Title = ViewBag.P_SiteName;
    ViewBag.Description = ViewBag.P_Description;
    ViewBag.Keywords = ViewBag.P_KeyWord;
    Layout = "~/Views/Shared/_LayoutLogin.cshtml";
}

<div class="container" style="text-align:center;padding:20px">
    <h2 style="color:#c6c6c6;font-family:Arial;font-size:16px;font-weight:bold">Please Enter Administrator Passwrd :</h2>
    <form class="form-inline" action="@Url.Action("Index","Argus")" method="post">
        <div class="form-group">
            <label class="sr-only" for="email">Email:</label>
            <input type="password" class="form-control" placeholder="Enter Password ..." id="Password" name="Password">
        </div>
        <button type="submit" class="btn btn-primary" style="margin-left:20px">Login to Argus</button>
    </form>
    <div>
        @if (ViewBag.ErrorLabel != "") { <label style="color:#d78484">@ViewBag.ErrorLabel</label> }
    </div>
</div>

Argus/Views/Shared/_LayoutCalculator.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <!-- Pre Define -->
    <title>@ViewBag.Title</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="@ViewBag.Description">
    <meta name="keywords" content="@ViewBag.Keywords">
    <meta name="robots" content="index, follow">
    <!-- Css Class -->
    <link href="~/Layout/assets/css/main2.css" rel="stylesheet" />
    <link href="~/Layout/assets/css/font-awesome.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
</head>
<body style="background-color:#202024">
    <!-- Responsice Menu -->
    <nav class="navbar navbar-inverse">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="@Url.Action("Index","Argus")"> Argus </a>
            </div>
            <div class="collapse navbar-collapse" id="myNavbar">
                <ul class="nav navbar-nav">
                    <li><a href="@Url.Action("Home","Argus")">Home</a></li>
                    <li><a href="@Url.Action("About","Argus")">About</a></li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    <li><a href="@Url.Action("Calculator","Argus")"><span class="btn btn-success">Calculator</span></a></li>
                </ul>
            </div>
        </div>
    </nav>
    <!-- Main Dynamic -->
    @RenderBody()
    <!-- Footer -->
    <footer id="footer">
        <div class="inner">
            <h2 style="color:#dbd8d8">WARNING : Disclaimer for Argus</h2>
            <p style="text-align:justify;text-justify:trim;color:#c6c6c6">
                We are doing our best to prepare the content of this site. However, for Argus cannot warranty the expressions and suggestions of the contents, as well as its accuracy. In addition, to the extent permitted by the law, for Argus shall not be responsible for any losses and/or damages due to the usage of the information on our website.
                <br>
                The links contained on our website may lead to external sites, which are provided for convenience only. Any information or statements that appeared in these sites are not sponsored, endorsed, or otherwise approved by for Argus. For these external sites, for Argus cannot be held liable for the availability of, or the content located on or through it. Plus, any losses or damages occurred from using these contents or the internet generally.
            </p>
            <ul class="icons" style="margin-top:40px">
                <li><a href="#" class="icon fa-twitter"><span class="label">Twitter</span></a></li>
                <li><a href="#" class="icon fa-facebook"><span class="label">Facebook</span></a></li>
                <li><a href="#" class="icon fa-instagram"><span class="label">Instagram</span></a></li>
                <li><a href="#" class="icon fa-envelope"><span class="label">Email</span></a></li>
            </ul>
            <p class="copyright" style="margin-top:40px">
                Developed By Hoogle Group &copy; All right Reserved - @DateTime.Now.Year.ToString()
            </p>
        </div>
    </footer>
    <!-- Scripts -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
    <script src="~/Layout/assets/js/jquery.scrolly.min.js"></script>
    <script src="~/Layout/assets/js/jquery.poptrox.min.js"></script>
    <script src="~/Layout/assets/js/main.js"></script>
    <script src="~/Layout/assets/js/skel.min.js"></script>
    <script src="~/Layout/assets/js/util.js"></script>
</body>
</html>

Argus/Views/Shared/_LayoutGraph.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <!-- Pre Define -->
    <title>@ViewBag.Title</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="@ViewBag.Description">
    <meta name="keywords" content="@ViewBag.Keywords">
    <meta name="robots" content="index, follow">
    <!-- Css Class -->
    <link href="~/Layout/assets/css/main.css" rel="stylesheet" />
    <link href="~/Layout/assets/css/font-awesome.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
</head>
<body style="background-color:#202024">
    <!-- Responsice Menu -->
    <nav class="navbar navbar-inverse">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="@Url.Action("Index","Argus")"> Argus </a>
            </div>
            <div class="collapse navbar-collapse" id="myNavbar">
                <ul class="nav navbar-nav">
                    <li><a href="@Url.Action("Home","Argus")">Home</a></li>
                    <li><a href="@Url.Action("About","Argus")">About</a></li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    <li><a href="@Url.Action("Calculator","Argus")"><span class="btn btn-success">Calculator</span></a></li>
                </ul>
            </div>
        </div>
    </nav>
    <!-- Main Dynamic -->
    @RenderBody()
    <!-- Footer -->
    <footer id="footer">
        <div class="inner">
            <h2 style="color:#dbd8d8">WARNING : Disclaimer for Argus</h2>
            <p style="text-align:justify;text-justify:trim;color:#c6c6c6">
                We are doing our best to prepare the content of this site. However, for Argus cannot warranty the expressions and suggestions of the contents, as well as its accuracy. In addition, to the extent permitted by the law, for Argus shall not be responsible for any losses and/or damages due to the usage of the information on our website.
                <br>
                The links contained on our website may lead to external sites, which are provided for convenience only. Any information or statements that appeared in these sites are not sponsored, endorsed, or otherwise approved by for Argus. For these external sites, for Argus cannot be held liable for the availability of, or the content located on or through it. Plus, any losses or damages occurred from using these contents or the internet generally.
            </p>
            <ul class="icons" style="margin-top:40px">
                <li><a href="#" class="icon fa-twitter"><span class="label">Twitter</span></a></li>
                <li><a href="#" class="icon fa-facebook"><span class="label">Facebook</span></a></li>
                <li><a href="#" class="icon fa-instagram"><span class="label">Instagram</span></a></li>
                <li><a href="#" class="icon fa-envelope"><span class="label">Email</span></a></li>
            </ul>
            <p class="copyright" style="margin-top:40px">
                Developed By Hoogle Group &copy; All right Reserved - @DateTime.Now.Year.ToString()
            </p>
        </div>
    </footer>
    <!-- Scripts -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
    <script src="~/Layout/assets/js/jquery.scrolly.min.js"></script>
    <script src="~/Layout/assets/js/jquery.poptrox.min.js"></script>
    <script src="~/Layout/assets/js/main.js"></script>
    <script src="~/Layout/assets/js/skel.min.js"></script>
    <script src="~/Layout/assets/js/util.js"></script>
</body>
</html>

Argus/Views/Shared/_LayoutMain.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <!-- Pre Define -->
    <title>@ViewBag.Title</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="@ViewBag.Description">
    <meta name="keywords" content="@ViewBag.Keywords">
    <meta name="robots" content="index, follow">
    <!-- Css Class -->
    <link href="~/Layout/assets/css/main.css" rel="stylesheet" />
    <link href="~/Layout/assets/css/font-awesome.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
</head>
<body style="background-color:#202024">
    <!-- Responsice Menu -->
    <nav class="navbar navbar-inverse">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="@Url.Action("Index","Argus")"> Argus </a>
            </div>
            <div class="collapse navbar-collapse" id="myNavbar">
                <ul class="nav navbar-nav">
                    <li><a href="@Url.Action("Home","Argus")">Home</a></li>
                    <li><a href="@Url.Action("About","Argus")">About</a></li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    <li><a href="@Url.Action("Calculator","Argus")"><span class="btn btn-success">Calculator</span></a></li>
                </ul>
            </div>
        </div>
    </nav>
    <!-- Scripts -->
    <section id="banner" style="background-image:url(../../Layout/images/bannerMain.jpg)">
        <div class="inner">
            <header>
                <h1>Argus</h1>
                <p>
                    Find the most suitable, convinient and efficient route in obtaining the Permanent Residency.
                </p>
            </header>
            <a href="#main" class="more">Learn More</a>
        </div>
    </section>
    <!-- Main Dynamic -->
    @RenderBody()
    <!-- Footer -->
    <footer id="footer">
        <div class="inner">
            <h2 style="color:#dbd8d8">WARNING : Disclaimer for Argus</h2>
            <p style="text-align:justify;text-justify:trim;color:#c6c6c6">
                We are doing our best to prepare the content of this site. However, for Argus cannot warranty the expressions and suggestions of the contents, as well as its accuracy. In addition, to the extent permitted by the law, for Argus shall not be responsible for any losses and/or damages due to the usage of the information on our website.
                <br>
                The links contained on our website may lead to external sites, which are provided for convenience only. Any information or statements that appeared in these sites are not sponsored, endorsed, or otherwise approved by for Argus. For these external sites, for Argus cannot be held liable for the availability of, or the content located on or through it. Plus, any losses or damages occurred from using these contents or the internet generally.
            </p>
            <ul class="icons" style="margin-top:40px">
                <li><a href="#" class="icon fa-twitter"><span class="label">Twitter</span></a></li>
                <li><a href="#" class="icon fa-facebook"><span class="label">Facebook</span></a></li>
                <li><a href="#" class="icon fa-instagram"><span class="label">Instagram</span></a></li>
                <li><a href="#" class="icon fa-envelope"><span class="label">Email</span></a></li>
            </ul>
            <p class="copyright" style="margin-top:40px">
                Developed By Hoogle Group &copy; All right Reserved - @DateTime.Now.Year.ToString()
            </p>
        </div>
    </footer>
    <!-- Scripts -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://code.jquery.com/jquery-1.11.2.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
    <script src="~/Layout/assets/js/jquery.scrolly.min.js"></script>
    <script src="~/Layout/assets/js/jquery.poptrox.min.js"></script>
    <script src="~/Layout/assets/js/main.js"></script>
    <script src="~/Layout/assets/js/skel.min.js"></script>
    <script src="~/Layout/assets/js/util.js"></script>
    <script src="content/bootstrapJS/jquery-2.1.1.min.js" type="text/javascript"></script>
</body>
</html>